#+OPTIONS: ^:nil
#+TITLE: SWHAM

* how to install
  - compile:
    #+BEGIN_SRC 
	g++ swham.cpp -lm -o swham.o
    #+END_SRC

* list of options:
  #+ATTR_HTML: :border 2 :rules all :frame border
  |---+-------------------------------------------------+---------|
  |   | simple description                              | default |
  |---+-------------------------------------------------+---------|
  | h | print out help information                      | -       |
  | d | input file of observations                      | -       |
  | f | input file of information of states             |         |
  | u | the type of potential function                  |         |
  | t | temperature                                     | -1.0    |
  | i | unit of potential energies in the input file    | -       |
  | o | unit of free energies of the output             | -       |
  | q | length of the equilibrium period                | -       |
  | n | number of the iterations                        | -       |
  | x | number of exchange attempts                     | -       |
  | s | print list of states                            | -       |
  | p | print list of observations                      | -       |
  | g | frequency of printing out free energy estimates |         |
  |---+-------------------------------------------------+---------|

** options and descriptions
*** -d observation_data_file
    This file contains $M$ blocks. Each block corresponds to a $\lambda$-state. At the beginning of each block, there
    are a comment line or multiple comment lines starting with "@" or "#". Do not leave blank lines between
    blocks. After comments lines, there is a $N_i \times K$ matrix, where $N_i$ is the total number of observations
    observed at the $i^{th}$ state and $K$ is the total number of properties of each observation. The matrix element
    $x_{jk}$ is the $k^{th}$ property of the $j^{th}$ observation observed at this $\lambda$-state. In SWHAM program,
    this matrix is stored in a three dimensional array "D". Its element "D[i][j][k]" is the $k^{th}$ property of the
    $j^{th}$ observation observed at the $i^{th}$ $\lambda$-state.

*** -f state_information_file
	This file contains $M$ lines. Each line represents a $\lambda$-state. If the value of temperature defined by "-t"
	option is negative, the first item of each line is the temperature of that $\lambda$-state. Usually, the next item
	of each line is the lambda value of that $\lambda$-state. The information of each state is stored in a two
	dimensional array "S" in SWHAM program. For example, element "S[i][0]" is the temperature of the $i^{th}$
	$\lambda$-state.

*** -t temperature
    The temperature of the simulations. This option is only useful when the simulations are run at a single
    temperature. In SWHAM, this value is stored in variable "temper". If "temper" is negative, the temperature of each
    state is defined be the first element of each line in the state_information_file, see option "-f".  If the value of
    "temper" is positive, "S[i][0]" of each $\lambda$-state is set to be "temper".

*** -u potential_function_type
	With array "D" and "S", the potential energy (biasing potential energy) can be calculated for each observation at
	any $\lambda$-state. Four different potential functions have been implemented in SWHAM code. 
	1) UWHAM-like input
	2) Temperature replica exchange
	3) Hamiltonian replica exchange
	4) Temperature and Hamiltonian replica exchange

*** -i input_unit -o output_unit
    The default unit for potential energies used in UWHAM is $k_B T$. However, if the data generated by simulations
    running at a single temperature, UWHAM program can read and output energies in a different unit. For these two
    options, "0" represents $k_B T$; "1" represents $kcal/mol$; and "2" represents "kJ/mol".

*** -n number_of_cycles
	Both RE-SWHAM and ST-SWHAM are run by cycles. This option specifies how many cycles to be run after equilibrium. 

*** -q equilibrium_length
	How many cycles for equilibrium. During the equilibrium, there is no output. 

*** -x number_of_exchange_attempts

*** -s 

*** -p

*** -g 
